ClassTable = {
    "Commerce":{"CT":"商務","Explaination":"For AKRS"},
    "Agriculture And Food Security":{"CT":"農業糧安","Explaination":"For AKRS"},
    "5G":{"CT":"5G通信"},
    "6G":{"CT":"6G通信"},
    "Academia":{"CT":"學術","Explaination":"學術界、學術研究"},
    "Academic Conference":{"CT":"學術年會"},
    "Academic Exchange":{"CT":"學術交流","Explaination":"(特定單位間的)學術交流"},
    "Academic Research":{"CT":"學術研究"},
    "Administration Reform":{"CT":"改革"},
    "Administration SM":{"CT":"行政短訊","Explaination":"例如要求繳交資料之短訊"},            
    "Additive Manufacturing":{"CT":"增材製造","Explaination":"例如：3D打印是一種可以用多種材料逐層生產三維零件的技術。"},
    "Aerospace":{"CT":"航太", "Explaination":"航太、飛機、太空船、太空站、航天技術、對地遙測等相關技術及應用"},
    "Afghanistan Affairs":{"CT":"阿富汗事務"},
    "Africa Affairs":{"CT":"非洲事務"},
    "Africa Economics":{"CT":"非洲經濟"},
    "African Swine Fever":{"CT":"非洲豬瘟"},
    "Agriculture And Fisheries":{"CT":"農林漁牧","Explaination":"如：農林漁牧、農業發展、糧食生產指數"},
    "AIIB":{"CT":"亞投行"},
    "Aircraft":{"CT":"航空器"},
    "Ant Group":{"CT":"螞蟻集團","Explaination":"螞蟻科技集團股份有限公司"},
    "Anti-Terrorism":{"CT":"反恐"},
    "APEC":{},
    "Artificial Intelligence":{"CT":"人工智慧"},
    "Astrophysics":{"CT":"天體物理學","Explaination":"天體物理學研究宇宙的物理學，這包括星體的物理性質（光度，密度，溫度，化學成分等等）和星體與星體彼此之間的交互作用。"},
    "Aviation Safety":{"CT":"航空安全"},
    "Augmented Reality":{"CT":"擴增實境"},
    "AUKUS":{"CT":"澳英美聯盟"},
    "ASEAN Affairs":{"CT":"東協事務"},
    "Asia Affairs":{"CT":"亞洲事務"},
    "Asia-Pacific Affairs":{"CT":"亞太事務"},
    "Asia-Pacific Economics":{"CT":"亞洲經濟"},
    "Asia-Pacific Security":{"CT":"亞洲安全"},
    "BCIM Economic Corridor":{"CT":"孟中印緬區域合作論壇"},
    "BTH Coordinated Development":{"CT":"京津冀協同發展","Explaination":"京津冀協同發展是涵蓋北京市、天津市和河北省的兩市一省的區域發展戰略，是中共十八大以來實現京津冀優勢互補、促進環渤海經濟區發展、帶動中國北方腹地發展的重大國家戰略。"},
    "Binhai New Area":{"CT":"濱海新區","Explaination":"濱海新區，簡稱濱城，是中華人民共和國天津市下轄的副省級區、國家級新區和國家綜合配套改革試驗區。"},
    "Bioenergy":{"CT":"生物能源","Explaination":"生物能源（Bioenergy）是從生物來源的材料製成的可再生能源，特色在於其可在生性，故傳統的煤碳、石油等不算。"},
    "Biology":{"CT":"生物學"},
    
    "Biotechnology":{"CT":"生物技術","Explaination":"生物技術（英語：biotechnology），又稱為生物科技，指利用生物體（含動物、植物及微生物的細胞）來生產有用的物質或改進製程，改良生物的特性，以降低成本及創新物種的科學技術。根據不同的工具和應用，它往往與生物工程和生物醫學工程的（相關）領域重疊。"},
    "Boao Forum":{"CT":"博鰲亞洲論壇","Explaination":"博鰲亞洲論壇（英語：Boao Forum for Asia）或稱亞洲論壇、亞洲博鰲論壇，由25個亞洲國家和澳洲發起（2006年增加至28個），於2001年2月27日在位於中國海南省瓊海市的萬泉河入海口的博鰲鎮召開大會後宣布成立，成立之時通過了《宣言》及《章程指導原則》等綱領性文件。論壇為非官方、非營利性、定期、定址的國際組織；為政府、企業及專家學者等提供一個共商經濟、社會、環境及其他相關問題的高層對話平台；海南博鰲為論壇總部的永久所在地。"},
    "Bohai Economic Rim":{"CT":"環渤海經濟區","Explaination":"環渤海經濟區指渤海周邊地區構成的經濟帶，為歐亞大陸橋東部起點之一。狹義上指京津冀地區、山東半島地區和遼中南地區構成的經濟圈；廣義上包括內蒙古自治區中部和山西省。"},
    "BR Affairs":{"CT":"巴西事務"},
    "BR Diplomacy":{"CT":"巴西外交"},
    "BR Economics":{"CT":"巴西經濟"},
    "BR Politics":{"CT":"巴西政治"},
    "BRICS":{"CT":"金磚五國"},
    "Business Management":{"CT":"企業管理"},
    "CAFTA":{"CT":"中國－東協自由貿易區","Explaination":"China–ASEAN Free Trade Area"},
    "Call For Conference Papers":{"CT":"學術年會徵稿"},
    "Call For Papers":{"CT":"學術徵稿","Explaination":"注意詐欺性論文徵稿屬Spam-Fraudulent Call For Papers類別"},
    "Carbon Neutrality":{"CT":"碳中和","Explaination":"碳中和、減碳、低碳"},
    "Carbon Capture And Storage":{"CT":"碳捕集與封存","Explaination":"碳捕集與封存是指收集從點源污染（如火力發電廠）產生的二氧化碳，將它們運輸至儲存地點並長期與空氣隔離的技術過程。"}, 
    "Central Asia Affairs":{"CT":"中亞事務"},
    "CICA":{"CT":"亞信會","Explaination":"亞洲相互協作與信任措施會議（英語：Conference on Interaction and Confidence-Building Measures in Asia (CICA)，簡稱亞信會議或亞信）是一個亞洲多國參與的論壇。"},
    "Civil Affairs":{"CT":"公民事務"},
    "Chemistry":{"CT":"化學","Explaination":"化學、化工"},
    "Chengdu-Chongqing Economic Circle":{"CT":"成渝地區雙城經濟圈"},
    "CELAC Affairs":{"CT":"拉丁美洲事務"},
    "Children Rights":{"CT":"兒童人權"},
    "CLEC":{"CT":"中老經濟走廊"},
    "Climatology":{"CT":"氣候學","Explaination":"例如：氣候變遷、極端氣候、氣象"},
    "Clinical Report":{"CT":"醫院臨床報告"},
    "CMEC":{"CT":"中緬經濟走廊"},
    "CN Administration":{"CT":"中國行政","Explaination":"例如：政務、廉政、行政執行、行政調查、社會治理作為"},
    "CN Affairs":{"CT":"中國事務"},
    "CN City Development":{"CT":"中國城市發展","Explaination":"例如：城市規劃、發展，智慧城市等"},
    "CN Civil Affairs":{"CT":"中國民政","Explaination":"便民、民生建設"},
    "CN Culture And History":{"CT":"中國文化與歷史"},
    "CN Debt-Trap Diplomacy":{"CT":"中國債務陷阱外交"},
    "CN Digital Economy":{"CT":"中國數位經濟"},
    "CN Diplomacy":{"CT":"中國外交"},
    "CN Economics":{"CT":"中國經濟","Explaination":"例如：經濟概論、經濟結構、經濟戰略、經濟形勢、總體經濟指數等尚較無明顯細分主題之文本"},
    "CN Economic Inequality":{"CT":"中國經濟不平等","Explaination":"收入不均、貧富不均等公平現象分析"},
    "CN FTZ":{"CT":"中國自由貿易區"},
    "CN FTZ-Fujian":{"CT":"福建自由貿易實驗區"},
    "CN FTZ-Guangdong":{"CT":"廣東自由貿易實驗區"},
    "CN FTZ-Hainan":{"CT":"海南自由貿易實驗區"},
    #"CN FTZ-Hainan FTP":{"CT":"海南自由貿易港"},
    "CN FTZ-Shandong":{"CT":"山東自由貿易實驗區"},
    "CN FTZ-Shanghai":{"CT":"上海自由貿易實驗區"},
    "CN FTZ-Tianjin":{"CT":"天津自由貿易實驗區"},
    "CN Income And Consumption":{"CT":"中國收入及消費","Explaination":"GDP、收入、消費支出等數據分析，Income And Consumption著眼人民個體生活品質。Rural Development農村發展則以村莊為考量主體。"},
    "CN Industrial Development":{"CT":"中國企業發展","Explaination":"產業發展情況、就業失業情況、產業創新"},
    "CN Industrial Investment":{"CT":"產業投資、招商、募資"},
    "CN Finance":{"CT":"中國金融","Explaination":"中國金融、融資、債務、金融發展政策等"},
    "CN Human Resource":{"CT":"中國人力資源"},
    "CN MediaW":{"CT":"中國媒體戰"},
    "CN Military":{"CT":"中國軍事"},
    "CN Military Administration":{"CT":"中國軍事行政"},
    "CN National Defense Operation":{"CT":"中國國防動員","Explaination":"如：救災"},
    "CN Military Diplomacy":{"CT":"中國軍事外交","Explaination":"如：出訪"},
    "CN Military Family":{"CT":"軍眷"},
    "CN Military Operation":{"CT":"軍事行動","Explaination":"如：演習、攻擊"},
    "CN Military Power":{"CT":"軍事力量","Explaination":"如：軍力分析"},
    "CN Military Recruitment":{"CT":"募兵"},
    "CN Real Estate Industry":{"CT":"中國房地產業","Explaination":"中國房地產、房價、建築業，產業資訊；另房地產物件資訊屬Real Estate Object。"},
    "CN Petitioning":{"CT":"中國上訪"},
    "CN Policy For TW":{"CT":"中國對台政策","Explaination":"中共對台政策，另中共涉台(對他國)外交亦暫列此類。"},
    "CN Politics":{"CT":"中國政治"},
    "CN Poverty Reduction":{"CT":"中國脫貧","Explaination":"中共脫貧、扶貧"},
    "CN Public Diplomacy":{"CT":"中國公共外交","Explaination":"中共公共外交，公共外交（Public Diplomacy）是指國家政府或政府協同民間力量，透過對外資訊傳播其文化及交流不同的方式，對他國民眾進行闡明、溝通與對話工作，希望創造有利於自身國之國際環境，進而謀求國家利益之最大化。 城市外交亦暫列於於本類。"},
    "CN Rural Development":{"CT":"中國農村發展","Explaination":"鄉村、農村發展及振興，Rural Development農村發展以村莊為考量主體，Income And Consumption則著眼人民個體生活品質。"},
    "CN Sports Diplomacy":{"CT":"體育外交"},
    "CN Strategy":{"CT":"中國國家發展戰略"},
    "CN Tax":{"CT":"中國稅收"},
    "CN Trade":{"CT":"中國貿易","Explaination":"中國對外貿易、進出口分析"},
    "CN Tourism Industry":{"CT":"中國旅遊業","Explaination":"旅遊業產業發展或政策"},
    "CN Technology":{"CT":"中國科技"},
    "CN Technology Company":{"CT":"中國科技公司","Explaination":"科技公司或科技園區，如：華為、中關村"},
    "CN Technology Project":{"CT":"中國科技項目","Explaination":"科技項目或科研相關，如：重點研發計劃"},
    "CN-AFR Cooperation":{"CT":"中非合作"},
    "CN-ARStates Cooperation":{"CT":"中阿合作"},
    "CN-ASEAN Cooperation":{"CT":"中國-東協合作"},
    "CN-AU Relations":{"CT":"中澳關係"},
    "CN-BR Relations":{"CT":"中國巴西關係"},
    "CN-CELAC Relations":{"CT":"中拉關係","Explaination":"中國拉丁美洲關係"},
    "CN-EURO BIT":{"CT":"中歐投資協定","Explaination":"中國-歐洲聯盟全面投資協定，又稱中歐投資協定、中歐雙邊投資協定、中歐全面投資協定、中歐BIT、中歐CAI，是中華人民共和國與歐洲聯盟的雙邊投資協定。"},
    "CN-EURO Relations":{"CT":"中歐關係"},
    "CN-EURO Cooperation":{"CT":"中歐合作"},
    "CN-FR Cooperation":{"CT":"中法合作"},
    "CN-FR Relations":{"CT":"中法關係"},
    "CN-IND Boundary":{"CT":"中印邊界","Explaination":"中印(度)邊界爭議"},
    "CN-IND Relations":{"CT":"中印關係","Explaination":"中印(度)關係"},
    "CN-INS Relations":{"CT":"中印尼關係","Explaination":"中印(尼)關係"},
    "CN-JP Relations":{"CT":"中日關係"},
    "CN-JP Trade":{"CT":"中日貿易"},
    "CN-JP-KOR FTA":{"CT":"中日韓自由貿易區"},
    "CN-KH Relations":{"CT":"中柬關係","Explaination":"中國-柬埔寨關係"},
    "CN-KOR Relations":{"CT":"中韓關係"},
    "CN-KOR Trade":{"CT":"中韓貿易"},
    "CN-LA Relations":{"CT":"中寮關係","Explaination":"中國-寮國關係"},
    "CN-MNG Relations":{"CT":"中蒙貿易","Explaination":"中國-蒙古關係"},
    "CN-NK Relations":{"CT":"中朝貿易","Explaination":"中國-朝鮮關係"},
    "CN-NP Relations":{"CT":"中尼泊爾關係"},
    "CN-NZ Relations":{"CT":"中紐關係","Explaination":"中國-紐西蘭關係"},
    "CN-PH Relations":{"CT":"中菲關係","Explaination":"中國-菲律賓關係"},
    "CN-PK Relations":{"CT":"中巴關係","Explaination":"中國-巴基斯坦關係"},
    "CN-RU Relations":{"CT":"中俄關係","Explaination":"中國-俄羅斯關係"},
    "CN-UK Relations":{"CT":"中英關係","Explaination":"中國-英國關係"},
    "CN-US Relations":{"CT":"中美關係","Explaination":"中國-美國關係"},
    "CN-US BIT":{"CT":"中美投資協定"},
    "CN-US Tech War":{"CT":"中美科技戰"},
    "CN-US Trade":{"CT":"中美貿易"},
    "CN-US Trade Disputes":{"CT":"中美貿易摩擦"},
    "CN-VN Relations":{"CT":"中越關係"},
    "Coal Supply And Demand":{"CT":"煤碳需求與供給"},
    "Compact With Africa":{"CT":"G20非洲契約"},
    "Confucius Institute":{"CT":"孔子學院"},
    "Constellation":{"CT":"星座文"},
    "Construction Industry":{"CT":"建築業"},
    "Contract For Purchase And Sales":{"CT":"彩購合同"},
    "Coronavirus Diplomacy":{"CT":"新冠肺炎外交"},
    "COVID-19":{"CT":"新冠肺炎"},
    "COVID-19 IPC":{"CT":"新冠肺炎疫控","Explaination":"新冠疫情防控作為(Infection Prevention And Control)"},
    "CPC Affairs":{"CT":"中共事務"},
    "CPC Meeting":{"CT":"中共會議","Explaination":"中共黨務相關會議通知、會議記錄"},
    "CPC Propaganda":{"CT":"中共黨宣"},
    "CPEC":{"CT":"中巴經濟走廊"},
    "CPTPP":{"CT":"跨太平洋夥伴全面進步協定（英語：Comprehensive and Progressive Agreement for Trans-Pacific Partnership，縮寫：CPTPP），原稱為跨太平洋戰略經濟夥伴關係協定（英語：The Trans-Pacific Partnership，縮寫：TPP）"},
    "CR Express":{"CT":"中歐班列","Explaination":"中歐班列，按照固定車次、線路、班期和全程運行時刻開行，往來於中國與歐洲以及一帶一路沿線各國的貨櫃國際鐵路聯運班列。"},
    "Cross-Strait Relations":{"CT":"兩岸關係"},
    "CSKFTA":{"CT":"中韓自貿協定"},
    "Customs Document":{"CT":"報關文件"},
    "Cybersecurity":{"CT":"網安","Explaination":"如：網路空間安全、網路空間博奕、網路空間治理"},
    "Data Science":{"CT":"資料科學"},
    "DE-AFR Relations":{"CT":"德非關係","Explaination":"德國-非洲關係"},
    "Diaoyutai Affairs":{"CT":"釣魚台事務"},
    "Digital Currency":{"CT":"數位貨幣","Explaination":"如：比特幣、臉書天秤幣、數位人民幣"},
    "Digital RMB":{"CT":"數位人民幣"},
    "Diplomacy":{"CT":"外交"},
    "Disaster Management":{"CT":"災害管理","Explaination":"自然災害預測及應對等、地震、風災研究。"},
    "Disclaimers":{"CT":"免責聲明","Explaination":"免責聲明制式文字"},
    "East Asia Affairs":{"CT":"東亞事務"},
    "Ecology":{"CT":"生態學"},
    "Education":{"CT":"教育","Explaination":"教育，通常有廣義和狹義兩種概念。廣義的教育泛指一切傳播和學習人類文明成果，即各種知識、技能和社會生活經驗，以促進個體社會化和社會個性化的社會實踐活動，產生於人類社會初始階段；狹義的教育專指學校教育，即制度化教育。廣義的教育則包含社會待人處事的方方面面，例如家教、禮儀等文明與社會的教育。"},
    "Education And Academia":{"CT":"教育及學術"},
    "Email Header":{"CT":"電子郵件header"},
    "Email Header-Email Address":{"CT":"電子郵件header信箱位址"},
    "Energy Consumption And Efficiency":{"CT":"能耗與效率","Explaination":"能耗、能源利用效率、用電量、節能"},
    "Energy Security":{"CT":"能源安全","Explaination":"wiki：能源安全是一國家安全名詞，為能源所帶來的潛在一切危害國家利益問題探討。偏向能源的管理及部署，如：電網、電力供給機制、高效能源利用、用電量等。油價波動、石油供給屬於子類Oil Supply And Demand。"},
    "Energy Technology":{"CT":"能源科技","Explaination":"能源科技暫定僅屬於Science And Technology子類，偏向技術面向。現不屬於Energy Security子類。"},
    "Engineering":{"CT":"電機","Explaination":"電機技術、工程技術"},
    "Environmental Monitoring Infrastructure":{"CT":"觀測基礎設施","Explaination":"如：科研觀測設施。衛星技術基於特殊性，佔列Aerospace類別。"},
    "Environmental Protection":{"CT":"環境保護"},
    "EURO-CELAC Cooperation":{"CT":"歐拉合作","Explaination":"歐洲-拉丁美洲合作"},
    "Europe Affairs":{"CT":"歐洲事務"},
    "Europe Economics":{"CT":"歐洲經濟"},
    "Exhibition":{"CT":"展覽"},
    "False Decoding":{"CT":"編碼錯誤"},
    "False Decoding-Broken Data Stream":{"CT":"毀損資料流","Explaination":"如莫名不斷重覆"},
    "False Decoding-PDF Binary":{"CT":"PDF二進位檔"},
    "Falun Gong":{"CT":"法輪功"},
    "Farmer Development":{"CT":"農民發展","Explaination":"農民就業、發展、扶助"},
    "Finance Disclaimer":{"CT":"金融免責聲明","Explaination":"金融免責聲明或風險聲明"},
    "Financial Industry":{"CT":"金融業","Explaination":"如：銀行業、保險業、信托業、證券業和租賃業"},
    "Financial Statements":{"CT":"財報","Explaination":"如：基金、債券財報"},
    "Fire News":{"CT":"火災新聞"},
    "Food Security":{"CT":"糧食安全"},
    "Foreign AdminReport":{"CT":"外國行政報告"},
    "Foreign Think":{"CT":"外國智庫"},
    "Formal Education":{"CT":"正規教育","Explaination":"如：小學、中學、高中、大學等"},
    "FTA":{"CT":"自由貿易協定","Explaination":"FTZ(Free Trade Zone)為自由貿易園區，FTA(Free Trade Area)為自由貿易區(自貿區)"},
    "FTAAP":{"CT":"亞太自由貿易區","Explaination":"亞洲太平洋自由貿易區（英語：Free Trade Area of the Asia-Pacific,FTAAP），簡稱亞太自由貿易區或亞太自貿區，是亞洲太平洋經濟合作組織（APEC）為了消除各成員國之間的貿易壁壘，推動亞太地區經濟一體化而設置的一種更高門檻的地區性自由貿易區。"},
    "FTP":{"CT":"自由貿易港"},
    "FTZ":{"CT":"自由貿易園區","Explaination":"FTZ(Free Trade Zone)為自由貿易園區，FTA(Free Trade Area)為自由貿易區(自貿區)"},
    "G7":{"CT":"七大工業國組織"},
    "G20":{"CT":"二十大工業國"},
    "Game":{"CT":"遊戲"},
    "Global Governance":{"CT":"全球治理"},
    "General Notifications":{"CT":"一般聲明","Explaination":"無價值之隱私政策聲明、智財權聲明"},
    "Genomics":{"CT":"基因組學","Explaination":"基因組學（英語：Genomics），或基因體學，是研究生物基因組和如何利用基因的一門學科。染色體亦暫列Genomics"},
    "Geographic Areas":{"CT":"地理區域"},
    "Geoscience":{"CT":"地球科學"},
    "Geopolitics":{"CT":"地緣政治"},
    "Global Law":{"CT":"國際法"},
    "Green Economy":{"CT":"綠色經濟","Explaination":"包含：低碳經濟、循環經濟等"},
    "Green Finance":{"CT":"綠色金融"},
    "Greater Bay Area":{"CT":"粵港澳大灣區","Explaination":"粵港澳大灣區是由圍繞中華人民共和國珠江三角洲地區伶仃洋組成的城市群。"},
    "Greater Mekong Subregion":{"CT":"大湄公河次區域經濟合作","Explaination":"大湄公河次區域經濟合作（英文：The Greater Mekong Subregion，縮寫：GMS）是基於湄公河流域的區域經濟合作機制，包括的國家有越南、柬埔寨、寮國、泰國、緬甸、中國。"},
    "Health Silk Road":{"CT":"健康絲綢之路",},
    "High Performance Computing":{"CT":"高速運算","Explaination":"高速運算、高容量計算(High-Capability Computing)"},
    "HK Affairs":{"CT":"香港事務"},
    "HK Economics":{"CT":"香港經濟"},
    "HK Finance":{"CT":"香港金融"},
    "HK National Security Law":{"CT":"香港國安法"},
    "HK Politics":{"CT":"香港政治","Explaination":"如：香港民運、香港一國兩制"},
    "HK Trade":{"CT":"香港貿易"},
    "Household":{"家居"},
    "Hospitality Industry":{"CT":"接待服務產業","Explaination":"如：住宿業、餐飲業"},
    "Hotel Affairs":{"CT":"飯店事務","Explaination":"如：私人訂房、Booking資訊，如為飯店促銷廣告或飯店資訊則屬Hotel Information"},
    "Hotel Information":{"CT":"飯店資訊","Explaination":"飯店資訊、飯店促銷、飯店評論等非私人訊息"},
    "Huawei Affairs":{"CT":"華為事務"},
    "Human Rights":{"CT":"人權"},
    "IND Affairs":{"CT":"印度事務"},
    "IND Diplomacy":{"CT":"印度外交"},
    "IND Military":{"CT":"印度軍事"},
    "IND Strategy":{"CT":"印度國家戰略"},
    "IND-PK Boundary":{"CT":"印巴邊界","Explaination":"印度-巴基斯坦邊界"},
    "IND-PK Relations":{"CT":"印巴關係","Explaination":"印度-巴基斯坦關係"},
    "Indo-Pacific Framework":{"CT":"印太框架、印太戰略"},
    "Informative":{"CT":"有意義資訊"},
    "Information Technology":{"CT":"資訊科技"},
    "Information Infrastructure":{"CT":"資訊基礎建設"},
    "Information System Message":{"CT":"資訊系統自動發送訊息"},
    "Infrastructure":{"CT":"基礎建設","Explaination":"基礎建設，包含：Information Infrastructure、Environmental Monitoring Infrastructure等子類。"},
    "Interior Affairs":{"CT":"內政事務"},
    "Internet Of Things":{"CT":"物聯網"},
    "Intellectual Property":{"CT":"智慧財產權"},
    "International Economics":{"CT":"國際經濟","Explaination":"如：國際經濟關係"},
    "International Finance":{"CT":"國際金融","Explaination":"如：國際金融關係、債務"},
    "International Relations":{"CT":"國際關係"},
    "ISM-Ecommerce Order":{"CT":"資訊系統自動發送訊息-電子商務訂購"},
    "ISM-Ecommerce Order-AliExpress":{"CT":"資訊系統自動發送訊息-阿里巴巴速買通"},
    "ISM-OA System Message":{"CT":"資訊系統自動發送訊息-OA系統通知"},
    "ISM-Security Verification Code":{"CT":"資訊系統自動發送訊息-安全驗證碼"},
    "ISM-Social Platform-FB":{"CT":"資訊系統自動發送訊息-Facebook"},
    "ISM-Social Platform-LinkedIn":{"CT":"資訊系統自動發送訊息-LinkedIn"},
    "ISM-Social Platform-Twitter":{"CT":"資訊系統自動發送訊息-推特"},
    "ISM-Undelivered Mail Notification Header":{"CT":"資訊系統自動發送訊息-未送達郵件"},
    "ISM-Warning Message":{"CT":"系統告警訊息"},
    "IR Affairs":{"CT":"伊朗事務"},
    "Jiangbei New Area":{"CT":"江北新區","Explaination":"江北新區是位於中華人民共和國江蘇省南京市的國家級新區。"},
    "Jiaodong Economic Circle":{"CT":"膠東經濟圈","Explaination":"膠東經濟圈位於山東半島沿海地區，面向日韓，有着對外開放的天然優勢。指導意見表示，膠東經濟圈應深度融入“一帶一路”建設——以中國—上海合作組織地方經貿合作示範區為帶領，打造“一帶一路”國際合作新平台"},
    "JP Affairs":{"CT":"日本事務"},
    "JP Diplomacy":{"CT":"日本外交"},
    "JP Economics":{"CT":"日本經濟"},
    "JP Finance":{"CT":"日本金融"},
    "JP Military":{"CT":"日本軍事"},
    "JP Politics":{"CT":"日本政治"},
    "JP Strategy":{"CT":"日本國家戰略"},
    "JP-EURO EPA":{"CT":"日本與歐盟經濟夥伴關係協定"},
    "JP-KOR Relations":{"CT":"日韓關係"},
    "JP-RU Relations":{"CT":"日俄關係"},
    "JP-UK Relations":{"CT":"日英關係"},
    "JP-US Relations":{"CT":"日美關係"},
    "Judiciary":{"CT":"司法"},
    "KOR Affairs":{"CT":"南韓事務"},
    "KOR Politics":{"CT":"南韓政治"},
    "KOR Diplomacy":{"CT":"南韓外交"},
    "L-M Cooperation":{"CT":"瀾湄合作","Explaination":"Lancang-Mekong Cooperation，瀾湄合作"},
    "Laser Physics And Technology":{"CT":"雷射物理及科技"},
    "Logistics Industry":{"CT":"物流業"},
    "Lottery":{"CT":"彩卷"},
    "Manufacturing":{"CT":"製造技術"},
    "Maritime Silk Road":{"CT":"海上絲綢之路"},
    "Materials Science":{"CT":"材料科學"},
    "Mathematics":{"CT":"數學"},
    "Medicine":{"CT":"醫學、藥學"},
    "Middle East Affairs":{"CT":"中東事務"},
    "Military":{"CT":"軍事"},
    "Military Diplomacy":{"CT":"軍事外交、防務外交"},
    "Military Exchanges":{"CT":"軍事交流"},
    "Military-Civil Fusion":{"CT":"軍民融合"},
    "Military Technology":{"CT":"軍事科技"},
    "Nanotechnology":{"CT":"奈米科技","Explaination":"奈米技術是一門應用科學，其目的在於研究於奈米規模時，物質和設備的設計方法、組成、特性以及應用。"},
    "Navigation Tags":{"CT":"網頁頁面分類標籤連結按紐"},
    "Navigational Warning":{"CT":"航行警告"},
    "Navigational Warning-Beacon And Buoy":{"CT":"航標相關航行警告"},
    "Navigational Warning-Cable Maintenance":{"CT":"佈纜、維修纜線相關航行警告"},
    "Navigational Warning-Dredging":{"CT":"疏浚相關航行警告"},
    "Navigational Warning-End Number Notice":{"CT":"航行警告尾號確認"},
    "Navigational Warning-Equipment Test":{"CT":"裝備測試相關航行警告"},
    "Navigational Warning-Event And Rescue":{"CT":"沉船類等需蒐救之事故相關航行警告及救援"},
    "Navigational Warning-Fairway":{"CT":"航道或特定大船航行路線相關航行警告"},
    "Navigational Warning-Hoisting":{"CT":"輪吊作業相關航行警告"},
    "Navigational Warning-LNG Carrier":{"CT":"液化天然氣運輸船相關航行警告"},
    "Navigational Warning-Marine Salvage":{"CT":"打撈相關航行警告"},
    "Navigational Warning-Maritime Research":{"CT":"海洋科研相關航行警告"},
    "Navigational Warning-Military":{"CT":"軍事相關航行警告"},
    "Navigational Warning-Non Traditional Security":{"CT":"非傳統安全相關航行警告"},
    "Navigational Warning-Obstacle Avoidance":{"CT":"航行障礙物規避相關航行警告"},
    "Navigational Warning-Petroleum Development":{"CT":"油氣開發相關航行警告"},
    "Navigational Warning-Routine Affairs":{"CT":"常規事務相關航行警告"},
    "Navigational Warning-Sea Drilling":{"CT":"海洋鑽井相關航行警告"},
    "Navigational Warning-Sea Trial":{"CT":"試航相關航行警告"},
    "Navigational Warning-Sports":{"CT":"帆船等體育活動相關航行警告"},
    "Navigational Warning-Submarine Work":{"CT":"水下作業相關航行警告"},
    "Navigational Warning-Towing":{"CT":"拖帶作業相關航行警告"},
    "Navigational Warning-Traffic Control":{"CT":"交通管制相關航行警告"},
    "New Type Of Major-Power Relationship":{"CT":"新型大國關係"},
    "New-Type Urbanization":{"CT":"新型城鎮化"},
    "NGO":{"CT":"非政府組織"},
    "Novel":{"CT":"小說"},
    "Novel-Natural Science":{"CT":"自然科學小說","Explaination":"如：科幻小說"},
    "Novel-Romance":{"CT":"言情小說"},
    "NK Affairs":{"CT":"北韓事務"},
    "NK Diplomacy":{"CT":"北韓外交"},
    "NK Military":{"CT":"北韓軍事"},
    "NK Nuclear Weapons":{"CT":"北韓核武"},
    "Northeast CN Affairs":{"CT":"中國東北事務"},
    "Nuclear Power":{"CT":"核能"},
    "Nuclear Weapons":{"CT":"核武"},
    "Oceanography":{"CT":"海洋學","Explaination":"海洋學、海洋科學研究潛艇、海洋學研究設備、研究計劃"},
    "OECD":{"CT":"經濟合作暨發展組織"},
    "Oil Supply And Demand":{"CT":"石油供需","Explaination":"石油供需、油價波動，如為開採技術等技術面向則屬Energy Technology。"},
    "Optics":{"CT":"光學"},
    "One Belt One Road":{"CT":"一帶一路"},
    "Pacific Alliance":{"CT":"太平洋聯盟","Explaination":"太平洋聯盟是一個拉丁美洲的貿易集團，現有四名正式成員：智利、哥倫比亞、墨西哥和秘魯。其宗旨為：「加強拉美太平洋沿岸國家貿易政策協調，促進聯盟內貨物、服務、資本和人員自由流通，致力於將聯盟打造成為對亞洲最具吸引力的拉美次區域組織和亞洲進入拉美市場最便利的入口。」"},
    "Paris Agreement":{"CT":"巴黎協定","Explaination":"《巴黎協定》是由聯合國195個成員國於2015年12月12日在2015年聯合國氣候峰會中通過的氣候協議；取代京都議定書，期望能共同遏阻全球暖化趨勢。"},
    "Particle Physics":{"CT":"粒子物理學","Explaination":"粒子物理學是研究組成物質和射線的基本粒子以及它們之間交互作用的一個物理學分支。由於許多基本粒子在大自然的一般條件下不存在或不單獨出現，物理學家只有使用粒子加速器在高能相撞的條件下才能生產和研究它們，因此粒子物理學也被稱為高能物理學。"},
    "PDF Format Description":{"CT":"PDF檔案的格式Code"},
    "Physics":{"CT":"物理學"},
    "PK Affairs":{"CT":"巴基斯坦事務"},
    "Plant Biology":{"CT":"植物學","Explaination":"植物學是一門研究植物形態解剖、生長發育、生理生態、系統進化、分類以及與人類的關係的綜合性科學，是生物學的分支學科。"},
    "Polar Affairs":{"CT":"極地事務"},
    "Polar Silk Road":{"CT":"極地絲綢之路"},
    "Pollution":{"CT":"污染"},
    "Population":{"CT":"人口議題","Explaination":"人口議題、老年化、結婚、生育、養老"},
    "Poverty Reduction":{"CT":"脫貧"},
    "Public Governance":{"CT":"公共治理"},
    "PRC-Boundary":{"CT":"中國邊界紛爭","Explaination":"如：中印邊界問題"},
    "PRC-Law":{"CT":"中國法律"},
    "PRC-Meeting":{"CT":"中國會議","Explaination":"非黨務之業務研討、行政研討相關會議通知、會議記錄"},
    "PRC-OffDoc":{"CT":"中共官方文件"},
    "PRC-Think":{"CT":"中共智庫文件"},
    
    "PRC-WReport":{"CT":"工作報告"},
    "Public Health":{"CT":"公衛"},
    "QUAD":{"CT":"四方安全對話","Explaination":"四方安全對話是美國、日本、印度和澳洲之間的非正式戰略對話。"},
    "Quantum Technology":{"CT":"量子科技"},
    "Quantum Information Technology":{"CT":"量子資訊科技"},
    "Rare-Earth Ore":{"CT":"稀土元素、礦物"},
    "RCEP":{"CT":"區域全面經濟夥伴協定"},
    "Real Estate Object":{"CT":"房地產物件"},
    "Rebalancing":{"CT":"亞洲再平衡"},
    "Recruitment":{"CT":"徵聘事務","Explaination":"如：徵人啓事、召聘"},
    "Recruitment Application":{"CT":"應徵申請"},
    "Recruitment Platform Message":{"CT":"應徵平台訊息"},
    "Robot":{"CT":"機器人"},
    "Report Form":{"CT":"報告表格"},
    "Report Form-Administration":{"CT":"行政部門表格","Explaination":"行政部門之表格，含有地名、行政區、單位等資訊之表格"},
    "Report Form-Unwanted":{"CT":"不需要之報告表格"},
    "Report Form-Uncertainty":{"CT":"尚未確定是否需要之表格類"},
    "Report Form-Technology Company":{"CT":"科技公司報表","Explaination":"科技公司、實驗室、中心之日報表、生產表或其他表格類，含有原物料等數據之表格"},
    "RMB":{"CT":"人民幣"},
    "RU Affairs":{"CT":"俄羅斯事務"},
    "RU Military":{"CT":"俄羅斯軍事"},
    "RU Strategy":{"CT":"俄羅斯國家戰略"},
    "SAFTZ":{"CT":"中非自貿區(協定)"},
    "SCO":{"CT":"上海合作組織","Explaination":"上海合作組織（簡稱上合組織；俄語：Шанха́йская организа́ция сотру́дничества，縮寫為 ШОС；英語：Shanghai Cooperation Organization，縮寫為 SCO）是中華人民共和國、俄羅斯、哈薩克、吉爾吉斯、塔吉克、烏茲別克、巴基斯坦、印度、伊朗等九國組成的國際組織，上海合作組織宣稱以「上海精神」解決各成員國間的邊境問題。"},
    "Science And Technology":{"CT":"科學與科技"},
    "Scrap":{"CT":"垃圾"},
    "Script Code":{"CT":"程式碼"},
    "Security In Space":{"CT":"太空安全"},
    "Semiconductor":{"CT":"半導體","Explaination":"半導體、晶片"},
    "Ship Movement Report":{"CT":"船報"},
    "Short Message":{"CT":"短訊"},
    "Showbiz":{"CT":"演藝圈","Explaination":"演藝圈、娛樂圈"},
    "Skill Training":{"CT":"教育訓練","Explaination":"教育訓練、培訓"},
    "Smart Manufacturing":{"CT":"智能製造"},
    "Social Insurance":{"CT":"社會保險","Explaination":"如：全民健保、勞保、養老保險"},
    "Social Security":{"CT":"社會安全"},
    
    "Society News":{"CT":"社會新聞"},
    "South Asia Affairs":{"CT":"南亞事務"},
    "South Sea":{"CT":"南海事務"},
    "Southeast Asia Affairs":{"CT":"東南亞事務"},
    "Spam":{"CT":"垃圾郵件"},
    "Sports":{"CT":"體育"},
    "Spam-Advertisement":{"CT":"廣告郵件"},
    "Spam-Advertisement-Training Course":{"CT":"廣告郵件-課程廣告"},
    "Spam-Advertisement-Sale":{"CT":"廣告郵件-售貨廣告"},
    "Spam-Advertisement-Sale-Finance":{"CT":"廣告郵件-金融廣告"},
    "Spam-Advertisement-Sale-Online Gambling":{"CT":"廣告郵件-線上賭博"},
    "Spam-Fraudulent Call For Papers":{"CT":"詐欺性論文徵稿"},
    "Spam-Phishing Attack":{"CT":"釣魚郵件攻擊"},
    "Spam-Porn":{"CT":"色情影片垃圾郵件"},
    "Spam-Porn-Hot Actress":{"CT":"色情影片垃圾郵件-人氣女優"},
    "Spam-Porn-OnePonDo":{"CT":"色情影片垃圾郵件-一本道"},
    "Spam-Porn-Tokyo Hot":{"CT":"色情影片垃圾郵件-東京熱"},
    "Spam-Receipt Affairs":{"CT":"開發票垃圾郵件"},
    "Straits Forum":{"CT":"海峽論壇","Explaination":"海峽論壇是台灣海峽兩岸中國大陸地區與台灣地區之間的民間交流平台，由國台辦、福建省人民政府及台灣一些民間團體等兩岸單位共同主辦"},
    "Strategic Partnership":{"CT":"戰略夥伴關係"},
    "Strategy And Security":{"CT":"戰略與安全"},
    "TFTA":{"CT":"(非洲)三合一自由貿易區","Explaination":"「三合一自由貿易區」將把現有的「南部非洲發展共同體」、「東非共同體」和「東南非共同市場」三個貿易體聯合起來。"},
    "The Americas Affairs":{"CT":"美洲事務"},
    "Tesla PDI Report":{"CT":"特斯拉交貨前檢驗報告"},
    "Tibet Affairs":{"CT":"西藏事務"},
    "Tourist Attraction":{"CT":"旅遊景點"},
    "TPP":{"CT":"跨太平洋夥伴全面進步協定"},
    "Transportation":{"CT":"交通運輸","Explaination":"交通網路、交通工具、自駕技術、高鐵外銷等"},
    "TW Diplomacy":{"CT":"臺灣外交"},
    "TW Affairs":{"CT":"臺灣事務"},
    "TW Law":{"CT":"臺灣法律"},
    "TW Politics":{"CT":"臺灣政治"},
    "TW-EURO Cooperation":{"CT":"臺歐合作","Explaination":"臺灣-歐洲合作"},
    "TW-JP Relations":{"CT":"臺日關係"},
    "TW-US Relations":{"CT":"臺美關係"},
    "UN Affairs":{"CT":"聯合國事務","Explaination":"如日本欲常任安理會等，另有子類UN Projects。"},
    "UN Projects":{"CT":"聯合國計劃","Explaination":"如2030年可持续发展议程等。另聯合國會議亦暫列此類，如：里約+20。"},
    "Unmanned Aerial Vehicle":{"CT":"無人機"},
    "US Diplomacy":{"CT":"美國外交"},
    "US Economics":{"CT":"美國經濟"},
    "US Finance":{"CT":"美國金融","Explaination":"美國金融、貨幣政策等。"},
    "US Military":{"CT":"美國軍事"},
    "US Politics":{"CT":"美國政治"},
    "US Strategy":{"CT":"美國國家戰略"},
    "US Technology":{"CT":"美國科技"},
    "US-ASEAN Relations":{"CT":"美國—東協關係"},
    "US-CN Strategic Security Dialogue":{"CT":"中美戰略安全對話"},
    "US-IR Relations":{"CT":"美國-伊朗關係"},
    "US-JP Relations":{"CT":"美日關係"},
    "US-JP Alliance":{"CT":"美日同盟"},
    "US-KOR Relations":{"CT":"美韓關係","Explaination":"美國-南韓關係"},
    "US-NK Relations":{"CT":"美朝關係","Explaination":"美國-朝鮮關係"},
    "US-RU Relations":{"CT":"美俄關係","Explaination":"美國-俄羅斯關係 "},
    "USMCA":{"CT":"美墨加協議","Explaination":"《美國－墨西哥－加拿大協議》（簡稱《美墨加協議》）是加拿大、墨西哥和美國之間的一項自由貿易協定。"},
    "Uncertainty":{"CT":"重要性待定分類"},
    "Uncertainty-Cells Of Figure":{"CT":"表格的單元格抽取結果"},
    "Uncertainty-Course List":{"CT":"學校課程清單"},
    "Uncertainty-Education Transcript":{"CT":"學校成績表單"},
    "Uncertainty-NonText Encoding":{"CT":"非純文字編碼"},
    "Uncertainty-NonText Encoding-Base64":{"CT":"Base64編碼"},
    "Uncertainty-NonText Encoding-Hex Code":{"CT":"16進制編碼"},  
    "Uncertainty-Private Delivery":{"CT":"私人物流"},
    "Uncertainty-Private Insurance Affairs":{"CT":"私人保險事務","Explaination":"如：保單、理賠"},
    "Uncertainty-Receipt":{"CT":"收據","Explaination":"收據、發票、帳單"},
    "Uncertainty-Receipt-Chartered":{"CT:渣打銀行電子帳單"},
    "Uncertainty-Receipt-Credit Card":{"CT":"信用卡電子帳單"},
    "Uncertainty-Receipt-Hinet":{"CT":"中華電信電子帳單"},
    "Uncertainty-Regular Report":{"CT":"週期性報告"},
    "Uncertainty-Regular Construction Report":{"CT":"定期施工報告"},
    "Uncertainty-Regular Maintenance Report":{"CT":"定期維護報告"},
    "Uncertainty-Regular Marketing Report":{"CT":"定期銷售報告"},
    "Uncertainty-Shipment Advice":{"CT":"發貨通知","Explaination":"發貨通知、運輸通知"},
    "Uncertainty-Table Of Contents":{"CT":"目錄片段"},
    
    "Uncertainty-Unidentified Digits":{"CT":"含有大量數字之未知意義串列"},
    "Uncertainty-VTC Information":{"CT":"VTC會議資訊"},
    "United Front":{"CT":"統一戰線","Explaination":"統一戰線，是一種由共产主义者（或其他人士）採用的政治鬥爭方式，指聯合及團結不同政治團體及社會各界的力量，為同一政治目的而共同奮鬥，其基礎理論由第三国际確立。"},
    "United Front In Taiwan":{"CT":"對臺統戰"},
    "Uranium Mining And Extraction":{"CT":"鈾開採及提取"},
    "Water Resource":{"CT":"水資源"},
    "Water-Energy-Food Nexus":{"CT":"水-能源-糧食安全紐帶"},
    "Weather News":{"CT":"天氣新聞及預報"},
    "Women Rights":{"CT":"婦女人權"},
    "WTO Affairs":{"CT":"WTO事務"},
    "Xiongan New Area":{"CT":"雄安新區","Explaination":"雄安新區是中國第19個國家級新區，也是首個由中共中央、國務院印發通知成立的國家級新區，位於河北省保定市東部，由雄縣、容城縣、安新縣及其周邊部分地區組成，於2017年4月1日正式成立。被官方定位為北京非首都功能疏解集中承載地。"},
    "Xinjiang Affairs":{"CT":"新疆事務"},
    "YD Integrated Development":{"CT":"長江三角洲區域一體化發展"},   
    "Email Disclaimer":{"CT":"電郵免責聲明"},
    "ED-Confidentiality Disclaimer":{"CT":"電郵免責聲明-機密聲明"},
    "ED-Negligence Disclaimer":{"CT":"電郵免責聲明-疏忽免責聲明"},
    "ED-Environmental Disclaimer":{"CT":"電郵免責聲明-環保聲明"},
    "ED-Virus Or Security Disclaimer":{"CT":"電郵免責聲明-病毒或安全免責聲明"},
    "ED-GDPR Disclaimer":{"CT":"電郵免責聲明-GDPR聲明","Explaination":"《一般資料保護規則》(General Data Protection Regulation)，又名《通用資料保護規則》，是在歐盟法律中對所有歐盟個人關於資料保護和隱私的規範，涉及了歐洲境外的個人資料出口。"},
    "ED-Disclaimers For Mailing Lists And Newsletters":{"CT":"電郵免責聲明-寄件清單聲明"},
    "ED-Contracts Disclaimer":{"CT":"電郵免責聲明-合約免責聲明"},
    "ED-Employees Liability Disclaimer":{"CT":"電郵免責聲明-雇員權力免責聲明"},
    "ED-Personal Opinion Disclaimer":{"CT":"電郵免責聲明-個人意見免責聲明"},
    "ED-Full Content Email Disclaimer":{"CT":"電郵免責聲明-完整內容免責聲明"},
    "ED-Copyright Disclaimer":{"CT":"電郵免責聲明-著作權免責聲明"},
    "ED-Legal Requirements Disclaimer":{"CT":"電郵免責聲明-法律要求免責聲明"},
    "ED-Interception And Monitoring Disclaimer":{"CT":"電郵免責聲明-截收及監控免責聲明"},
    "ED-Enquiries Disclaimer":{"CT":"電郵免責聲明-查詢免責聲明"},
    "ED-HIPAA Disclaimer":{"CT":"電郵免責聲明-HIPAA免責聲明","Explaination":"《健康保險隱私及責任法案》(Health Insurance Portability and Accountability Act)是美國在1996年所頒布，醫療行業必須遵守的法案。該法案制定了一系列安全標準，就保健計劃、供應商以及結算中心如何以電子文件的形式來傳送、訪問和存儲受保護的健康信息做出詳細的規定。"},
    "ED-Automated Email Disclaimer":{"CT":"電郵免責聲明-自動化電郵聲明"},
    }
